export default Object.freeze({
  LISTING_DETAILS: "Guidance Details",
  LOGIN: "Login",
  REGISTER: "Register",
  LISTINGS: "Guidance",
  RECORD: "Record",
  ACCOUNT: "Account",
  MESSAGE_DETAILS: "Message Details",
  CHAT_DETAILS: "Chat Details",
  USERS_INFO: "User Info",
  QUESTIONNAIRE_STEP1: "Supplementary Info",
  QUESTIONNAIRE_STEP2: "One More Question!",
  IDFINDER_STEP2: "User Info Details",
  Feedback: "My Feedbacks",
});
